name: wtelegramclient

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Run script
        env:
          api_id: ${{ secrets.APP_ID }}
          api_hash: ${{ secrets.API_HASH }}
          bot_token: ${{ secrets.BOT_TOKEN }}
          MESSAGE_LINK: ${{ secrets.MESSAGE_LINK }}
        run: |
          echo "Beginning WTelegramClient test"
          mkdir -p out
          cd src/wtelegramclient
          dotnet run src/wtelegramclient
          cd ../..

      - name: Commit and push changes
        run: |
          LIBRARY="WTelegramClient" ./.github/_commit.sh
